# Generated by Django 2.0.2 on 2019-09-28 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('promises', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(default=0), size=None)),
            ],
        ),
    ]
