# Generated by Django 2.0.2 on 2019-09-28 12:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webreceiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.TextField(default='')),
                ('sender', models.BigIntegerField(default=0)),
                ('receiver', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Promises',
            fields=[
                ('promiseid', models.TextField(default='', primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('metrics', models.TextField(default='')),
                ('category', models.IntegerField(default=0)),
                ('wall_pub', models.BooleanField(default=False)),
                ('story_pub', models.BooleanField(default=False)),
                ('exp_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transactions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='debted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='promises',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
